version: 2.1
jobs:
  setup-python-venv:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - restore_cache:
          keys: 
            - python-venv-a-{{ checksum "requirements.txt" }}
            - python-venv-a-
      - run:
          name: setup python venv and install requirements
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths: [.venv]
          key: python-venv-a-{{ checksum "requirements.txt" }}
  
  setup-hadolint:
    docker:
      - image: cimg/python:3.9.2
    environment:
      HADOLINT_DL_ADDR: "https://github.com/hadolint/hadolint/releases/download/v1.23.0/hadolint-Linux-x86_64"
    steps:
      - restore_cache:
          keys: 
            - hadolint-$HADOLINT_DL_ADDR
      - run:
          name: install hadolint binary
          command: |
            if [ ! -f ./hadolint/hadolint ] ; then
              mkdir -p hadolint/ || true
              wget -O ./hadolint/hadolint $HADOLINT_DL_ADDR
              chmod +x ./hadolint/hadolint
            fi
      - save_cache:
          paths: [hadolint]
          key: hadolint-$HADOLINT_DL_ADDR

  lint-app:
    docker:
        - image: cimg/python:3.9.2
    steps:
      - checkout
      - restore_cache:
          keys: 
            - python-venv-a-{{ checksum "requirements.txt" }}
            - python-venv-a-
      - run:
          name: linting application and smoke test
          command: |
            . .venv/bin/activate
            pylint *.py
  lint-dockerfile:
    docker:
        - image: cimg/python:3.9.2
    steps:
      - checkout
      - restore_cache:
          keys: 
            - hadolint-$HADOLINT_DL_ADDR
            - hadolint-
      - run:
          name: linting application dockerfile
          command: |
            ./hadolint/hadolint Dockerfile

workflows:
  default:
    jobs:
      - setup-python-venv
      - setup-hadolint
      - lint-app:
          requires: [setup-python-venv, setup-hadolint]
      - lint-dockerfile:
          requires: [setup-hadolint]

          