version: 2.1
jobs:
  setup-python-venv:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - restore_cache:
          keys: 
            - python-venv-{{ checksum "requirements.txt" }}
            - python-venv-
      - run:
          name: setup python venv and install requirements
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths: [frontend/node_modules]
          key: python-venv-{{ checksum "requirements.txt" }}

workflows:
  default:
    jobs:
      - setup-python-venv