apiVersion: v1
kind: Service
metadata:
  name: cowsay-web-rolling-update
  labels:
    app: cowsay-web-rolling-update
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: cowsay-web-rolling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay-web-rolling-update
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cowsay-web-rolling
  template:
    metadata:
      labels:
        app: cowsay-web-rolling
        role: rolling-update
    spec:
      containers:
      - name: cowsay-web-container
        image: ttannhaeuser/cowsay-web:latest
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0